{
 "title": "Github workflows and repositories",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "repository",
    "label": "Repository",
    "query": {
     "query": "label_values(github_repository, repository)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Respositories", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Repository visibility summary",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(github_repository{repository=~\"$repository\"}) by(visibility)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "topk(1,last_over_time(github_repository{repository=~\"$repository\"}[$__range])) by (full_name)"
    }
   ]
  },
  {
   "title": "Opened Pull Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(github_pull_request{repository=~\"$repository\", state=\"open\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pull requests",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 8 },
   "targets": [
    {
     "expr": "bottomk(1,sort(last_over_time(github_pull_request{repository=~\"$repository\"}[$__range]))) by (number)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Actions Workflows ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Workflows summary status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count_over_time(github_actions_workflow_run{conclusion=~\"success|failure|startup_failure|cancelled\",repository=~\"${repository}\"}[$__range])) by (conclusion)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(count(count_over_time(github_actions_workflow_run{status=\"completed\",repository=~\"${repository}\", conclusion=\"success\"}[$__range])) by (run_number, workflow_id)) / count(count(count_over_time(github_actions_workflow_run{status=\"completed\",repository=~\"${repository}\"}[$__range])) by (run_number, workflow_id)))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queued",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(github_actions_workflow_run{status=\"queued\",repository=~\"${repository}\"})"
    }
   ]
  },
  {
   "title": "Workflow latenty ( seconds )",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "topk(1,max_over_time(github_actions_workflow_run_latency{repository=~\"$repository\"}[$__range])) by (workflow_id,run_number)"
    }
   ]
  },
  {
   "title": "In Progress ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(github_actions_workflow_run{status=\"in_progress\",repository=~\"${repository}\"})"
    }
   ]
  },
  {
   "title": "Workflows queued",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "github_actions_workflow_runs_queued{repository=~\"$repository\"}",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "Workflows in progress",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "github_actions_workflow_runs_in_progress{repository=~\"$repository\"}",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "Count workflow ( by user )",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(count(last_over_time(github_actions_workflow_run[$__range])) by (author_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflows details",
   "type": "table",
   "gridPos": { "h": 14, "w": 15, "x": 9, "y": 33 },
   "targets": [
    {
     "expr": "topk(1,max_over_time(github_actions_workflow_run{repository=~\"$repository\"}[$__range])) by (workflow_id,run_number)"
    }
   ]
  },
  { "title": "API Rate limits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Rate limit",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "github_api_rate_limit", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "github_api_rate_used", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Reset",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "github_api_rate_reset - time()", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Usage %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(github_api_rate_used/github_api_rate_limit)*100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}